name: Windows Release Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-sign-publish:
    name: Build, Sign & Publish
    runs-on: windows-latest
    permissions:
      contents: write  # 需要写权限上传 Release 文件

    steps:
      # ---------- 初始化环境 ----------
      - name: Checkout code
        uses: actions/checkout@v4

      # ---------- 清理 Rust 缓存 ----------
      - name: Purge Rust cache
        run: |
          cargo clean
          Remove-Item -Recurse -Force ~/.cargo/registry
          Remove-Item -Recurse -Force ~/.cargo/git

      # ---------- 配置 Node.js 环境 ----------
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      # ---------- 配置 Rust 工具链 ----------
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: x86_64-pc-windows-msvc

      # ---------- 安装 Tauri CLI ----------
      - name: Install Tauri
        run: npm install -g @tauri-apps/cli

      # ---------- 安装项目依赖 ----------
      - name: Install dependencies
        run: |
          npm install
          cd src-tauri
          cargo generate-lockfile  # 预生成锁文件
          cd ..

      # ---------- 修复锁文件问题 ----------
      - name: Fix Cargo.lock
        run: |
          cd src-tauri
          # 强制删除旧锁文件并重新生成
          Remove-Item -Force Cargo.lock -ErrorAction SilentlyContinue
          cargo generate-lockfile
          cd ..

      # ---------- 构建签名步骤 ----------
      - name: Build Windows MSI
        run: npm run tauri build -- --target x86_64-pc-windows-msvc
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}

      # ---------- 生成更新清单 ----------
      - name: Generate Update Manifest
        shell: pwsh
        run: |
          $version = $env:GITHUB_REF -replace 'refs/tags/v', ''
          $msiName = "font-viewer_${version}_x64_en-US.msi"
          $sigContent = Get-Content "src-tauri/target/release/$msiName.sig" -Raw

          # 使用 Here-String 生成 JSON
          @"
          {
            "version": "$version",
            "notes": "Automated release",
            "pub_date": "$(Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ")",
            "platforms": {
              "windows-x86_64": {
                "signature": "$sigContent",
                "url": "https://github.com/chatterjay/font-viewer/releases/download/v$version/$msiName"
              }
            }
          }
          "@ | Out-File -Encoding utf8 latest.json

      # ---------- 发布到 GitHub Releases ----------
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            src-tauri/target/release/*.msi
            latest.json
          draft: false
          prerelease: false